apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provider-aws-ocp
  namespace: provider-aws-ocp
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
