apiVersion: v1
kind: Secret
metadata:
  name: provider-aws-ocp-ssh-private-key
  namespace: provider-aws-ocp
stringData:
  ssh-privatekey: |-
    -----BEGIN RSA PRIVATE KEY-----
    xx
    -----END RSA PRIVATE KEY-----
type: Opaque
