apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: ocp-worker
  namespace: ocp
spec:
  clusterDeploymentRef:
    name: ocp
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: t3a.large
  replicas: 3
