apiVersion: v1
kind: Secret
metadata:
  name: ocp-ssh-private-key
  namespace: ocp
stringData:
  ssh-privatekey: |-
    -----BEGIN RSA PRIVATE KEY-----
    xx
    -----END RSA PRIVATE KEY-----
type: Opaque
