apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  finalizers:
    - hive.openshift.io/deprovision
  labels:
    cloud: AWS
    cluster.open-cluster-management.io/clusterset: managed
    hive.openshift.io/cluster-platform: aws
    hive.openshift.io/cluster-region: ap-south-1
    region: ap-south-1
    vendor: OpenShift
  name: provider-aws-ocp-1
  namespace: provider-aws-ocp-1
spec:
  baseDomain: sebastian-colomar.com
  clusterName: provider-aws-ocp-1
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    aws:
      credentialsSecretRef:
        name: provider-aws-ocp-1-aws-creds
      region: ap-south-1
  provisioning:
    imageSetRef:
      name: img4.12.6-multi-appsub
    installConfigSecretRef:
      name: provider-aws-ocp-1-install-config
    sshPrivateKeySecretRef:
      name: provider-aws-ocp-1-ssh-private-key
  pullSecretRef:
    name: provider-aws-ocp-1-pull-secret
