apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: provider-aws-ocp-1-infra
  namespace: provider-aws-ocp-1
spec:
  clusterDeploymentRef:
    name: provider-aws-ocp-1
  labels:
    node-role.kubernetes.io/infra: ""
  name: infra
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: t3a.large
  replicas: 3
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
