apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: provider-aws-ocp-1-worker
  namespace: provider-aws-ocp-1
spec:
  clusterDeploymentRef:
    name: provider-aws-ocp-1
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: t3a.large
  replicas: 3
