apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: provider-vsphere-ocp-1-infra
  namespace: provider-vsphere-ocp-1
spec:
  clusterDeploymentRef:
    name: provider-vsphere-ocp-1
  labels:
    node-role.kubernetes.io/infra: ""
  name: infra
  platform:
    vsphere:
      coresPerSocket: 2
      cpus: 4
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 3
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
