apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provider-vsphere-ocp-1
  namespace: provider-vsphere-ocp-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: provider-vsphere-ocp-1
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
