apiVersion: v1
kind: Secret
metadata:
  name: provider-vsphere-ocp-1-install-config
  namespace: provider-vsphere-ocp-1
stringData:
  install-config.yaml: |
    apiVersion: v1
    baseDomain: xxx
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform:
        vsphere:
          coresPerSocket: 2
          cpus: 4
          memoryMB: 16384
          osDisk:
            diskSizeGB: 120
      replicas: 3
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform:
        vsphere:
          coresPerSocket: 2
          cpus: 4
          memoryMB: 16384
          osDisk:
            diskSizeGB: 120
      replicas: 3
    metadata:
      name: provider-vsphere-ocp-1
    networking:
      clusterNetwork:
      - cidr: 10.131.0.0/16
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.1.0.0/16
      networkType: OVNKubernetes
      serviceNetwork:
      - 172.31.0.0/16
    platform:
      vsphere:
        apiVIP: 1.1.1.1
        cluster: xxx
        datacenter: xxx
        defaultDatastore: xxx 
        folder: xxx
        ingressVIP: 1.1.1.2
        network: xxx
        password: xxx
        resourcePool: xxx
        username: xxx
        vCenter: xxx
    proxy:
      httpProxy: http://xxx:1111
      httpsProxy: http://xxx:1111
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        ssh-rsa xxx
type: Opaque
